[options]
HoldPkg      = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Local repo containing calamares built from AUR by build.sh
[vertex-local]
SigLevel = Optional TrustAll
Server = file:///var/cache/vertex-linux/local-repo
