W = Window.GetWidth();
H = Window.GetHeight();

Window.SetBackgroundTopColor(0.059, 0.039, 0.102);
Window.SetBackgroundBottomColor(0.059, 0.039, 0.102);

logo_raw    = Image("logo.png");
LOGO_W      = 200;
LOGO_H      = Math.Int(logo_raw.GetHeight() * LOGO_W / logo_raw.GetWidth());
logo_img    = logo_raw.Scale(LOGO_W, LOGO_H);
logo_sprite = Sprite(logo_img);
logo_sprite.SetX(Math.Int((W - LOGO_W) / 2));
logo_sprite.SetY(Math.Int((H - LOGO_H) / 2));
logo_sprite.SetZ(1);
