---
defaultGroups:
    - name: wheel
      state: true
    - name: audio
      state: true
    - name: video
      state: true
    - name: network
      state: true
    - name: storage
      state: true
    - name: optical
      state: true
    - name: lp
      state: true
    - name: scanner
      state: true

autologinGroup:  autologin
doAutologin:     false

sudoersGroup:    wheel
setRootPassword: true
doReusePassword: false

passwordRequirements:
    minLength: 8
    maxLength: -1

userShell: /bin/bash
