# Vertex Linux – Calamares installer settings
---
modules-search: [ /usr/lib/calamares/modules ]

instances:
    - id: squashfs-check
      module: shellprocess
      config: shellprocess-squashfs-check.conf
    - id: postinstall
      module: shellprocess
      config: shellprocess-postinstall.conf

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - summary
    - exec:
        - partition
        - mount
        - shellprocess@squashfs-check
        - unpackfs
        - machineid
        - fstab
        - locale
        - keyboard
        - localecfg
        - users
        - networkcfg
        - hwclock
        - services-systemd
        - packages
        - shellprocess@postinstall
        - umount
    - show:
        - finished

branding: vertex
prompt-install: true
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: true
quit-at-end: false
